services:
  db:
    image: "postgres:17.2-alpine"
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "${DB_HOST}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express
    restart: always
    environment:
      - DB_HOST=db
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
